spring:
  datasource:
    url: jdbc:mysql://localhost:3306/withSpacedb?serverTimezone=Asia/Seoul
    username: withSpaceAdmin
    password: hansung369
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  security: # 소셜 로그인 관련
    oauth2:
      client:
        registration:
          google:
            client-id: 662421055588-ukpf87c2rlq04uk2vs4pm7qlt1qq9th1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
#  file:
#    name: my-application.log
#    path: /path/to/log/file
#  level:
#    org.hibernate.SQL: debug
