spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/withSpacedb?serverTimezone=Asia/Seoul
#    username: withSpaceAdmin
#    password: hansung369
    url: jdbc:mysql://withspace-api.cneerh3s692r.ap-northeast-2.rds.amazonaws.com:3307/withSpacedb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dongjun
    password: hansung1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  file:
    name: my-application.log
    path: /path/to/log/file
#  level:
#    org.hibernate.SQL: debug