spring:
  datasource:
    url: jdbc:mysql://localhost:3306/withSpacedb?serverTimezone=Asia/Seoul
    username: withSpaceAdmin
    password: hansung369
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
  file:
    name: my-application.log
    path: /path/to/log/file
#  level:
#    org.hibernate.SQL: debug